# TPM 插件
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'christoomey/vim-tmux-navigator'

# vim-tmux-navigator: 禁用 prefix + C-l 的清屏绑定，交给 bindings.conf 的分屏绑定
set -g @vim_navigator_prefix_mapping_clear_screen ""

# tokyo-night-tmux 配置
set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @tokyo-night-tmux_show_datetime 1
set -g @tokyo-night-tmux_date_format YMD
set -g @tokyo-night-tmux_time_format 24H
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative
set -g @tokyo-night-tmux_show_netspeed 1
set -g @tokyo-night-tmux_show_battery_widget 1
set -g @tokyo-night-tmux_show_hostname 1
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_wbg 0

# tmux-resurrect 配置
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes ':all:'

# tmux-continuum 配置
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

# TPM 初始化（放在文件末尾）
set -g @tpm-install '~/.config/tmux/plugins/tpm/bin/install_plugins'
set -g @tpm-clean '~/.config/tmux/plugins/tpm/bin/clean_plugins'
set -g @tpm-update '~/.config/tmux/plugins/tpm/bin/update_plugins'
run '~/.config/tmux/plugins/tpm/tpm'
